### ISSUE TITLE
Numpy inconsistency in mat_discover

### ISSUE THREAD

**Issue by ancarnevali** [sparks-baird/mat_discover#53]
Hi!
After pip-installing mat_discover in a new conda environment, I found the following potential problem:
```
>>> from mat_discover.mat_discover_ import Discover   
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\anton\anaconda3\envs\mat-disc\lib\site-packages\mat_discover\mat_discover_.py", line 36, in <module>
    import umap
  File "C:\Users\anton\anaconda3\envs\mat-disc\lib\site-packages\umap\__init__.py", line 2, in <module>
    from .umap_ import UMAP
  File "C:\Users\anton\anaconda3\envs\mat-disc\lib\site-packages\umap\umap_.py", line 28, in <module>
    import numba
  File "C:\Users\anton\anaconda3\envs\mat-disc\lib\site-packages\numba\__init__.py", line 200, in <module>
    _ensure_critical_deps()
  File "C:\Users\anton\anaconda3\envs\mat-disc\lib\site-packages\numba\__init__.py", line 140, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.21 or less")
ImportError: Numba needs NumPy 1.21 or less
```
After which I downgraded my numpy to 1.21.0 via pip install. I was prompted the following error:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
matminer 0.7.6 requires numpy>=1.22.0, but you have numpy 1.21.0 which is incompatible.
```
I am currently on numpy 1.21.0, and everything seems to work, but perhaps this incompatibility is worth a thought?

**Comment by sgbaird** [comment]
Do you mind doing `pip freeze` in your base environment and posting the result here?

This is a good point - I'm surprised it didn't automatically install NumPy 1.21.0, so I'm wondering if this has anything to do with settings for the base environment.

I've gotten similar warnings, but usually it runs fine without any intervention on my part. `mat_discover` doesn't depend on `matminer` and at some point the conflict might disappear as Numba supports higher versions.

Thanks for letting me know about this. I'll take another look into it.

**Comment by ancarnevali** [comment]
sure! Here's pip freeze's result:
```
(base) C:\Users\anton>pip freeze
aioitertools==0.9.0
anaconda-clean @ file:///C:/ci/anaconda-clean_1614068963676/work
anyio==3.5.0
atomate==1.0.3
backports.lzma==0.0.14
bcrypt==3.2.0
boto3==1.21.2
botocore==1.24.2
brotlipy==0.7.0
castepxbin==0.1.0
certifi==2021.10.8
cffi==1.15.0
charset-normalizer @ file:///tmp/build/80754af9/charset-normalizer_1630003229654/work
click==8.0.3
conda==4.11.0
conda-package-handling @ file:///C:/ci/conda-package-handling_1618262410900/work
cryptography==36.0.1
custodian==2022.2.13
dnspython==2.2.0
emmet==2018.6.7
emmet-core==0.21.19
fastapi==0.74.0
FireWorks==2.0.2
Flask==2.0.3
flask-paginate==2022.1.8
gunicorn==20.1.0
h5py==3.6.0
idna @ file:///tmp/build/80754af9/idna_1637925883363/work
inflect==5.4.0
itsdangerous==2.1.0
Jinja2==3.0.3
jmespath==0.10.0
jsonschema==4.4.0
maggma==0.41.0
MarkupSafe==2.1.0
matminer==0.7.6
menuinst==1.4.16
mongogrant==0.3.3
mongomock==4.0.0
paramiko==2.9.2
phonopy==2.13.1
prettyplotlib==0.1.7
pycosat==0.6.3
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pymatgen-analysis-diffusion==2022.1.15
PyNaCl==1.5.0
pyOpenSSL @ file:///opt/conda/conda-bld/pyopenssl_1643788558760/work
PySocks @ file:///C:/ci/pysocks_1605307512533/work
pywin32==302
requests @ file:///opt/conda/conda-bld/requests_1641824580448/work
robocrys==0.2.7
ruamel-yaml-conda @ file:///C:/ci/ruamel_yaml_1616016898638/work
s3transfer==0.5.1
seekpath==2.0.1
six @ file:///tmp/build/80754af9/six_1644875935023/work
sshtunnel==0.4.0
starlette==0.17.1
sumo==2.2.5
tqdm @ file:///tmp/build/80754af9/tqdm_1635330843403/work
urllib3 @ file:///opt/conda/conda-bld/urllib3_1643638302206/work
win-inet-pton @ file:///C:/ci/win_inet_pton_1605306162074/work
wincertstore==0.2
```
I found this issue only when installing in local, it's never thrown in colab.
When running Discover() no clear `numpy` conflicts appear, indeed.

**Comment by sgbaird** [comment]
I think that the issue has to do with `matminer` being installed into the base environment. In other words, there are conflicts between the new environment you made and your base environment. I'm guessing that this issue goes away with a clean base environment (i.e. one without `matminer`). If you still run into issues, let me know, and feel free to reopen this.
